services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stan
      POSTGRES_PASSWORD: stan
      POSTGRES_DB: stan
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
